#!/usr/bin/env python3
"""Export a complete synthetic-runnable OpenFOAM adapter package.

The old exporter copied a generated case and emitted echo-only launchers.  It
now delegates to the shared route package generator, then adds the native case
when one has already been generated by the OpenFOAM bridge.  It never claims
that the external solver ran.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
from pathlib import Path


def _generator_module():
    path = Path(__file__).resolve().parents[1] / "simulation-package" / "generate_package.py"
    spec = importlib.util.spec_from_file_location("pt_simulation_package_generator", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load package generator: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("case_dir", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    case = args.case_dir.resolve()
    output = args.output.resolve()
    if output.exists():
        parser.error(f"refusing to overwrite existing package: {output}")
    spec_path = case / "simulation_spec.yaml"
    runtime_path = case / "runtime.yaml"
    source_case = case / "openfoam" / "generated_case"
    if not spec_path.is_file() or not runtime_path.is_file():
        parser.error("simulation_spec.yaml and runtime.yaml are required before export")
    if not source_case.is_dir():
        parser.error("generated OpenFOAM case is required before export")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    runtime = json.loads(runtime_path.read_text(encoding="utf-8"))
    generator = _generator_module()
    generator.generate_package("openfoam_continuum", output, spec.get("selected_model_id") or "openfoam-case")
    native_case = output / "native" / "openfoam-case"
    shutil.copytree(source_case, native_case)
    (output / "runtime.yaml").write_text(json.dumps(runtime, indent=2) + "\n", encoding="utf-8")
    (output / "simulation-spec.yaml").write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    manifest_path = output / "simulation_package_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    implementation = manifest.setdefault("implementation", {})
    implementation.setdefault("solver_native_files", []).append("native/openfoam-case")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
